services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1.5G"
